language: go

go:
  - 1.14

before_install:
  - echo  before_install

script:
  - echo  script

before_deploy:
  - GOARCH=arm GOOS=linux   go build -a -v  -o netspeed-linux-arm
  - GOARCH=386 GOOS=linux   go build  -a -v -o netspeed-linux-386
  - GOARCH=386 GOOS=darwin  go build -a -v -o netspeed-darwin-386
  - GOARCH=386 GOOS=windows go build -a -v -o netspeed-windows-386.exe
  - GOARCH=mipsle GOOS=linux   go build -a -v -o netspeed-linux-mipsle
  - GOARCH=amd64 GOOS=linux   go build -a -v -o netspeed-linux-amd64
  - GOARCH=amd64 GOOS=darwin  go build -a -v -o netspeed-darwin-amd64
  - GOARCH=amd64 GOOS=windows go build -a -v -o netspeed-windows-amd64.exe
  - GOARCH=mips64le GOOS=linux   go build -a -v -o netspeed-linux-mips64le
  - zip -r netspeed-linux-arm.zip netspeed-linux-arm
  - zip -r netspeed-linux-mipsle.zip netspeed-linux-mipsle
  - zip -r netspeed-linux-386.zip netspeed-linux-386
  - zip -r netspeed-darwin-386.zip netspeed-darwin-386
  - zip -r netspeed-darwin-amd64.zip netspeed-darwin-amd64
  - zip -r netspeed-linux-amd64.zip netspeed-linux-amd64
  - zip -r netspeed-windows-386.zip netspeed-windows-386.exe
  - zip -r netspeed-windows-amd64.zip netspeed-windows-amd64.exe
  - zip -r netspeed-linux-mips64le.zip netspeed-linux-mips64le

deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  skip_cleanup: true
  file:
    - netspeed-linux-arm.zip
    - netspeed-linux-386.zip
    - netspeed-darwin-386.zip
    - netspeed-windows-386.zip
    - netspeed-linux-mipsle.zip
    - netspeed-linux-amd64.zip
    - netspeed-darwin-amd64.zip
    - netspeed-windows-amd64.zip
    - netspeed-linux-mips64le.zip
  on:
    tags: true
    all_branches: true
    go: 1.14
