language: go

go:
  - 1.20

before_install:
  - echo  before_install

script:
  - echo  script

before_deploy:
  - GOARCH=amd64 GOOS=linux   go build -a -v -o netspeed-linux-amd64
  - GOARCH=loong64 GOOS=linux   go build -a -v -o netspeed-linux-loong64  
  - GOARCH=amd64 GOOS=windows go build -a -v -o netspeed-windows-amd64.exe
  - zip -r netspeed-linux-amd64.zip netspeed-linux-amd64
  - zip -r netspeed-windows-amd64.zip netspeed-windows-amd64.exe
  - zip -r netspeed-windows-loong64.zip netspeed-windows-amd64.exe

deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  skip_cleanup: true
  file:
    - netspeed-linux-amd64.zip
    - netspeed-windows-amd64.zip
    - netspeed-windows-loong64.zip
  on:
    tags: true
    all_branches: true
    go: 1.20
