language: go

go:
  - 1.14

before_install:
  -

script:
  - 

before_deploy:
  - GOARCH=arm GOOS=linux   go build -o netspeed-linux-arm
  - GOARCH=386 GOOS=linux   go build -o netspeed-linux-386
  - GOARCH=386 GOOS=darwin  go build -o netspeed-darwin-386
  - GOARCH=386 GOOS=windows go build -o netspeed-windows-386.exe
  - GOARCH=amd64 GOOS=linux   go build -o netspeed-linux-amd64
  - GOARCH=amd64 GOOS=darwin  go build -o netspeed-darwin-amd64
  - GOARCH=amd64 GOOS=windows go build -o netspeed-windows-amd64.exe
  - mv README.md README.txt
  - zip -r netspeed-linux-arm.zip netspeed-linux-arm
  - zip -r netspeed-linux-386.zip netspeed-linux-386
  - zip -r netspeed-darwin-386.zip netspeed-darwin-386
  - zip -r netspeed-linux-amd64.zip netspeed-linux-amd64
  - zip -r netspeed-darwin-amd64.zip netspeed-darwin-amd64
  - zip -r netspeed-windows-386.zip netspeed-windows-386.exe
  - zip -r netspeed-windows-amd64.zip netspeed-windows-amd64.exe

deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  skip_cleanup: true
  file:
    - netspeed-linux-arm.zip
    - netspeed-linux-386.zip
    - netspeed-darwin-386.zip
    - netspeed-windows-386.zip
    - netspeed-linux-amd64.zip
    - netspeed-darwin-amd64.zip
    - netspeed-windows-amd64.zip
    - netspeed-windows-gui-386.zip
    - netspeed-windows-gui-amd64.zip
  on:
    branch: master
    go: 1.14
